# Site Settings
title: toaster.cc
description: "Not a site about toasters."
baseurl: ""
url: "https://toaster.cc"
author: "Angus Pearson"
author_avatar: "//s.gravatar.com/avatar/8c54ddeaeca4f852c1d522c83780ced1?s=160"

## COLOURS
# Copy (main text) colour
copy_colour: "#090b2c"

# Primary and Accent (Compliment) colour:
theme_colour: "#0072ff"
theme_complement: "#d5006f" #"#d6577e" #"#da7951" #"#004499"

# :selection and mark colour
select_colour: "desaturate(lighten(rgb(0, 114, 255), 42%), 10%)"

# If the theme colour is light, darken it this much
# for text or other elements on white
theme_colour_copy_darken: "20%"

# Colour to make the hero's scrim
# default is rgba(0,0,0,0.3)
scrim_colour: "rgba(0, 114, 255, 0.4)"

## HERO IMAGE
hero_image: "forum-col-opt.jpg"

# Pantone colour of the year: Serenity 2016 #9ac6ff and Rose Quartz #f7cac9
# TCC blue: #9ac6ff
# TCC green: #59d380 & comp: #bdeecd
# TCC yellow: #fed136

# Main Navigation (Manual)
navigation:
 - text: Home
   url: /
 - text: Portfolio
   url: /portfolio/
 - text: Posts
   url: /posts/
 - text: Archive
   url: /posts/archive/

# Build Settings
future: false
show_drafts: false
paginate: 3
paginate_path: "posts/page:num"
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
highlighter: rouge
plugins: [jekyll-paginate]
sass:
  style: compressed


# Addition content types
collections:
  projects:
    output: false
  unlisted:
    output: true
    layout: clear
    permalink: /unlisted/:path/

