# Site Settings
title: toaster.cc
description: "toaster.cc - AngusP's place on the net"
baseurl: ""
url: "http://toaster.cc"
author: "Angus Pearson"

# Main Navigation (Manual)
navigation:
 - text: Home
   url: /
 - text: Posts
   url: /posts/
 - text: GitHub
   abs: https://github.com/AngusP

# Build Settings
paginate: 3
paginate_path: "posts/page:num"
markdown: kramdown
permalink: pretty
highlighter=rouge

# Post-like content
collections:
- projects