# Site Settings
title: toaster.cc
description: "toaster.cc - AngusP's place on the net"
baseurl: ""
url: "http://toaster.cc"
author: "Angus Pearson"
theme_colour: "#fed136"
theme_complement: "#fed136"

# Pantone colour of the year: #f7cac9
# Complementary: #92a8d1
# That^tm yellow: #fed136

# Main Navigation (Manual)
navigation:
 - text: Home
   url: /
 - text: Portfolio
   url: /portfolio/
 - text: Posts
   url: /posts/

# Build Settings
paginate: 3
paginate_path: "posts/page:num"
markdown: kramdown
permalink: pretty
highlighter: rouge
gems: [jekyll-paginate]
sass:
  style: compressed


# Addition content types
collections:
- projects
