# Site Settings
title: toaster.cc
description: "Not a site about toasters."
baseurl: ""
url: "http://toaster.cc"
author: "Angus Pearson"
author_avatar: "//s.gravatar.com/avatar/8c54ddeaeca4f852c1d522c83780ced1?s=160"

## COLOURS
# Primary and Accent (Compliment) colour:
theme_colour: "#9ac6ff"
theme_complement: "#f7cac9"

# :selection and mark colour
select_colour: "saturate(lighten(#9ac6ff, 10%), 10%)"

# If the theme colour is light, darken it this much
# for text or other elements on white
theme_colour_copy_darken: "20%"

# Colour to make the hero's scrim
# default is rgba(0,0,0,0.3)
scrim_colour: "darken(rgba(154, 198, 255, 0.3), 20%)"

## HERO IMAGE
hero_image: "rain-opt.jpg"

# Pantone colour of the year: 2016 #f7cac9 and Rose Quartz #f7cac9
# TCC blue: #9ac6ff
# TCC green: #59d380 & comp: #bdeecd
# TCC yellow: #fed136

# Main Navigation (Manual)
navigation:
 - text: Home
   url: /
 - text: Portfolio
   url: /portfolio/
 - text: Posts
   url: /posts/
 - text: Archive
   url: /posts/archive/

# Build Settings
future: false
show_drafts: false
paginate: 3
paginate_path: "posts/page:num"
markdown: kramdown
permalink: pretty
highlighter: rouge
gems: [jekyll-paginate]
sass:
  style: compressed


# Addition content types
collections:
  projects:
    output: false
  unlisted:
    output: true
    layout: clear
    permalink: /unlisted/:path/

